### ISSUE TITLE
Imagens no drive

### ISSUE THREAD

**Issue by BrunoAlm** [BrunoAlm/lejaum.inc-react#11]
Algumas imagens que estão no figma não estão no drive
![image](https://user-images.githubusercontent.com/65208006/210140714-cd94db31-2602-4666-a62b-a43f604eee27.png)
![image](https://user-images.githubusercontent.com/65208006/210140721-c3d76a4f-d1f8-414d-a830-51b5121e0f1b.png)

- [x] Order poker;
- [x] Parceiro bonés;
- [x] Agro diamantino;
- [x] melhores sinais;
- [x] Carrossel musta;

**Comment by lejaum** [comment]
Até agora todos os arquivos estão ok 🤙🤙

**Comment by BrunoAlm** [comment]
lindo
