### ISSUE TITLE
Design First Screen

### ISSUE THREAD

**Issue by lejaum** [BrunoAlm/lejaum.inc-react#7]
> Foi solicitado para o nosso setor de copywriting liberar um cta estratégico para inserir na first screen, mas quando essa alteração chegar provavelmente a gente já refez o site todo. Por ser um alteração textual não vamos fazer questão de alterar agora.

- [x] As boxes com as frases serão um carrossel só que vão se movendo com o tempo, um card slider;

O tempo pra se mover pode ser uns 3 segundos;

**Comment by BrunoAlm** [comment]
Só falta alterar um pouco o espaçamento dependendo do tamanho da tela, aí ja ta joia
